"""fourth Migration

Revision ID: 2a12f966913e
Revises: 6c3a968171c8
Create Date: 2019-09-26 19:39:01.727993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a12f966913e'
down_revision = '6c3a968171c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writers', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('writers', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writers', 'profile_pic_path')
    op.drop_column('writers', 'bio')
    # ### end Alembic commands ###
