"""second Migration

Revision ID: 467cc26ff9dc
Revises: d2d30c6fd89f
Create Date: 2019-09-26 10:22:11.473169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467cc26ff9dc'
down_revision = 'd2d30c6fd89f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writers', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writers', 'pass_secure')
    # ### end Alembic commands ###
