"""third Migration

Revision ID: 6c3a968171c8
Revises: 467cc26ff9dc
Create Date: 2019-09-26 12:02:19.646491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3a968171c8'
down_revision = '467cc26ff9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writers', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_writers_email'), 'writers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_writers_email'), table_name='writers')
    op.drop_column('writers', 'email')
    # ### end Alembic commands ###
