"""seventh Migration

Revision ID: d653b027954b
Revises: 53a3fdef4392
Create Date: 2019-09-27 19:16:17.169453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd653b027954b'
down_revision = '53a3fdef4392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_writer_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'writer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('writer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_writer_id_fkey', 'comments', 'writers', ['writer_id'], ['id'])
    # ### end Alembic commands ###
